export const TempCategories = [
  {
    title: "Moldova Agroindbank",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Maib_ID_new_artwork_colour.png",
    top_img:"https://www.maib.md/storage/media/2022/07/26//image_1658826536_3fRqo4D2tI.png",
    score: 4.4,
    reviews: 100,
    city: "Chisinau, Moldova",
    site: "maib.md",
    route: "/maib",
    site_link: "https://www.maib.md",
    location: "Chisinau, Constantin Tănase street, 9/1",
    about:"With more than 25 years of experience, Moldova Agroindbank continues to be a well-known brand in Moldova and abroad. MAIB is a top universal bank on the Moldovan market. It provides a full range of financial products and services to individuals and legal entities, through multiple distribution channels, including branches, agencies, a wide network of ATMs and POS terminals, as well as remote banking services (Internet banking, Mobile banking), etc.",
    schedule:"9:00-17:00",
    phone:"1313",
  },

  {
    title: "Fincombank",
    logo: "https://www.fincombank.com/files/images/2022/logo-fincombank.png",
    top_img:"https://www.bizlaw.md/uploads/article/20189/626a8b5072e93.jpg",
    score: 3.5,
    reviews: 50,
    city: "Chisinau, Moldova",
    site: "fincombank.com",
    route: "/fcb",
    site_link: "https://www.fincombank.com",
    location: "Chisinau, bd. Stefan cel Mare, 6",
    about:"FinComBank now has over 29 years of activity, being one of the top 5 most popular banks in Moldova, which has 80 branches and agencies throughout the country. Year after year, the Bank discovers new horizons, delights its customers with new achievements and is constantly growing in number of customers, in number of employees, but above all in terms of high quality banking services, respecting international standards and being innovative in many aspects of banking.",
    schedule:"9:00-18:00",
    phone:"022 269 999",
  },

  {
    title: "Victoriabank",
    logo: "https://upload.wikimedia.org/wikipedia/ro/thumb/8/82/Victoriabank_logo.svg/2560px-Victoriabank_logo.svg.png",
    top_img:"https://www.mold-street.com/bma_userfiles/image/victoriabank%20sucursala%2024%20ore.jpg",
    score: 3,
    reviews: 30,
    city: "Chisinau, Moldova",
    site: "victoriabank.md",
    route: "/vb",
    site_link: "https://www.victoriabank.md",
    location: "Chisinau, bd. Moscova, 16",
    about:"Victoriabank is a Moldovan brand with a unique, authentic story – an innovator that is linked to the first bank card, the first ATM, the first mobile application and the first credit for small entrepreneurs in the Republic of Moldova. There are over 270,000 active customers, 100 offices of Victoriabank in over 30 localities in the country. The number of employees of the bank exceeds 1,000 people, with an average age of 34 years. Among them there are people employed in the first years since its founding.",
    schedule:"9:00-17:00",
    phone:"1303",
  },
]